### PR TITLE
Fix trim attributes

### LINKED ISSUE #171: Bug report: Unwrapped type name truncating type name
A use case for Sourcery requires using `MethodParameter`'s `typeName` without any attributes (specifically, I'd like to remove the `@escaping` attribute). There's no way to do that currently without using `unwrappedTypeName`. Here's an example of what I've tried:

`{% for method in type.NetworkProtocol.methods %}
    let {{ method.shortName }}CallTracker = MockMethodCallTracker<({% for parameter in method.parameters %}{{ parameter.typeName }}{% if parameter.name != method.parameters.last.name %}, {% endif %}{% endfor %}), {{ method.returnTypeName }}>()
{% endfor %}`

This should output:
`let getLatestOpportunityCallTracker = MockMethodCallTracker<(ConversationListApiResponse), Request?>()`

Instead, we get `let getLatestOpportunityCallTracker = MockMethodCallTracker<(@escaping ConversationListApiResponse), Request?>()`

If I try changing `{{ parameter.typeName }}` to `{{ parameter.unwrappedTypeName }}`, I get an unexpected name out: it outputs `let getLatestOpportunityCallTracker = MockMethodCallTracker<(ConversationListApiRespo), Request?>()`. Looks like it's truncating from the beginning and end of the word instead of just the beginning?

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #171

### CODE REVIEW

File: SourceryTests/Models/MethodSpec.swift [hunk 1]
```diff
@@ -84,21 +84,10 @@ class MethodSpec: QuickSpec {
 
         describe("MethodParameter") {
 
-            context("given optional parameter type with short syntax") {
```
Comment (krzysztofzablocki) [inline SourceryTests/Models/MethodSpec.swift]: why is this removed though?

Comment (ilyapuchka) [inline SourceryTests/Models/MethodSpec.swift]: it's a part of TypedSpec already
