### PR TITLE
fixed parsing protocol methods return types followed by attributes

### LINKED ISSUE #596: Regression in 0.12 with attributes
Using the SwiftyMocky `Mock.swifttemplate` with `0.12` on a protocol with functions using `@discardableResult` attributes yields this code:
screen shot 2018-04-11 at 3 49 49 pm
 Before this release the code generated did not have these problems so it appears to be a regression.

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #596

### CODE REVIEW

File: SourceryRuntime/Sources/Attribute.swift [hunk 1]
```diff
@@ -12,6 +12,8 @@ import Foundation
     // sourcery: skipJSExport
     let _description: String
 
+    public var __parserData: Any?
```
Comment (SourceryBot) [inline SourceryRuntime/Sources/Attribute.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/krzysztofzablocki/Sourcery/blob/48ec95c431065cf834fe3e13335a35f7da73b0f9/SourceryRuntime/Sources/Attribute.swift#L15"></span>Undocumented symbol.</td>
    </tr>
  </tbody>
</table>
